export type CatalogueEntry = {
  letter: string;
  subcategory: string;
  products: string[];
};

export const INDUSTRIAL_CATALOGUE: CatalogueEntry[] = [
  { letter: 'A', subcategory: 'Air Equipment', products: ['Air Compressors', 'Air Dryers', 'Air Receivers', 'Air Hoses', 'Air Regulators', 'Air Filters', 'Air Tools'] },
  { letter: 'A', subcategory: 'Abrasives', products: ['Grinding Wheels', 'Sandpaper', 'Flap Discs', 'Wire Brushes', 'Cutting Discs'] },
  { letter: 'A', subcategory: 'Adhesives', products: ['Epoxy', 'Thread Lockers', 'Silicone Sealants', 'PU Adhesives'] },
  { letter: 'B', subcategory: 'Bearings', products: ['Ball Bearings', 'Roller Bearings', 'Pillow Block Bearings', 'Linear Bearings'] },
  { letter: 'B', subcategory: 'Bolts & Fasteners', products: ['Bolts', 'Nuts', 'Washers', 'Studs', 'Rivets', 'Anchors'] },
  { letter: 'B', subcategory: 'Belts', products: ['V-Belts', 'Timing Belts', 'Conveyor Belts'] },
  { letter: 'C', subcategory: 'Cutting Tools', products: ['Drill Bits', 'End Mills', 'Hole Saws', 'Reamers', 'Taps & Dies'] },
  { letter: 'C', subcategory: 'Chains', products: ['Roller Chains', 'Conveyor Chains', 'Lifting Chains'] },
  { letter: 'C', subcategory: 'Cables', products: ['Power Cables', 'Control Cables', 'Welding Cables'] },
  { letter: 'C', subcategory: 'Chemicals', products: ['Degreasers', 'Solvents', 'Rust Removers', 'Lubricants'] },
  { letter: 'D', subcategory: 'Drills', products: ['Magnetic Drills', 'Hammer Drills', 'Bench Drills'] },
  { letter: 'D', subcategory: 'Dust Collection', products: ['Dust Extractors', 'Cyclones', 'Dust Filters'] },
  { letter: 'D', subcategory: 'Diesel Equipment', products: ['Fuel Pumps', 'Fuel Tanks', 'Fuel Filters'] },
  { letter: 'E', subcategory: 'Electric Motors', products: ['AC Motors', 'DC Motors', 'Servo Motors', 'Gear Motors'] },
  { letter: 'E', subcategory: 'Electrical Equipment', products: ['MCCBs', 'MCBs', 'Contactors', 'Relays', 'Switches'] },
  { letter: 'E', subcategory: 'Extension Cords', products: ['Industrial Power Cords'] },
  { letter: 'F', subcategory: 'Fans', products: ['Axial Fans', 'Centrifugal Fans', 'Exhaust Fans'] },
  { letter: 'F', subcategory: 'Filters', products: ['Hydraulic Filters', 'Air Filters', 'Fuel Filters', 'Oil Filters', 'Water Filters'] },
  { letter: 'F', subcategory: 'Forklift Accessories', products: ['Fork Extensions', 'Fork Positioners'] },
  { letter: 'G', subcategory: 'Gearboxes', products: ['Helical Gearboxes', 'Worm Gearboxes', 'Planetary Gearboxes'] },
  { letter: 'G', subcategory: 'Generators', products: ['Diesel Generators', 'Petrol Generators'] },
  { letter: 'G', subcategory: 'Gauges', products: ['Pressure Gauges', 'Temperature Gauges'] },
  { letter: 'H', subcategory: 'Hydraulic Equipment', products: ['Hydraulic Pumps', 'Hydraulic Cylinders', 'Power Packs', 'Hydraulic Valves', 'Hydraulic Hoses'] },
  { letter: 'H', subcategory: 'Hand Tools', products: ['Wrenches', 'Pliers', 'Screwdrivers', 'Hammers'] },
  { letter: 'H', subcategory: 'Hoists', products: ['Electric Hoists', 'Chain Hoists', 'Lever Hoists'] },
  { letter: 'I', subcategory: 'Industrial Lighting', products: ['LED Flood Lights', 'High Bay Lights'] },
  { letter: 'I', subcategory: 'Inverters', products: ['VFDs', 'Solar Inverters'] },
  { letter: 'I', subcategory: 'Insulation', products: ['Pipe Insulation', 'Thermal Insulation'] },
  { letter: 'J', subcategory: 'Jacks', products: ['Hydraulic Bottle Jacks', 'Floor Jacks'] },
  { letter: 'J', subcategory: 'Jib Cranes', products: ['Wall Mounted Jib Cranes', 'Free Standing Jib Cranes'] },
  { letter: 'K', subcategory: 'Knives', products: ['Utility Knives', 'Industrial Blades'] },
  { letter: 'K', subcategory: 'Key Stock', products: ['Shaft Keys', 'Key Bars'] },
  { letter: 'L', subcategory: 'Ladders', products: ['Aluminum Ladders', 'Fiberglass Ladders'] },
  { letter: 'L', subcategory: 'Lifting Equipment', products: ['Slings', 'Shackles', 'Hooks', 'Chain Blocks'] },
  { letter: 'L', subcategory: 'Lubrication Systems', products: ['Grease Guns', 'Oil Pumps'] },
  { letter: 'M', subcategory: 'Measuring Tools', products: ['Calipers', 'Micrometers', 'Laser Measures'] },
  { letter: 'M', subcategory: 'Machine Tools', products: ['Lathe', 'Milling Machines', 'CNC Machines'] },
  { letter: 'M', subcategory: 'Material Handling', products: ['Trolleys', 'Pallet Trucks', 'Carts'] },
  { letter: 'N', subcategory: 'Nozzles', products: ['Spray Nozzles', 'Fuel Nozzles'] },
  { letter: 'N', subcategory: 'Nuts', products: ['Stainless Nuts', 'Lock Nuts'] },
  { letter: 'O', subcategory: 'Oil Equipment', products: ['Oil Pumps', 'Oil Skimmers', 'Oil Drainers'] },
  { letter: 'O', subcategory: 'O-Rings', products: ['Nitrile O-Rings', 'Viton O-Rings', 'EPDM O-Rings'] },
  { letter: 'P', subcategory: 'Pumps', products: ['Centrifugal Pumps', 'Diaphragm Pumps', 'Gear Pumps', 'Vacuum Pumps'] },
  { letter: 'P', subcategory: 'Pneumatic Equipment', products: ['Air Cylinders', 'Pneumatic Valves', 'FRL Units'] },
  { letter: 'P', subcategory: 'Pipes', products: ['PVC Pipes', 'Steel Pipes', 'Copper Pipes', 'Stainless Pipes'] },
  { letter: 'P', subcategory: 'PPE', products: ['Helmets', 'Gloves', 'Safety Shoes', 'Goggles'] },
  { letter: 'Q', subcategory: 'Quick Couplings', products: ['Hydraulic Quick Connectors', 'Pneumatic Quick Connectors'] },
  { letter: 'R', subcategory: 'Rollers', products: ['Conveyor Rollers', 'Paint Rollers'] },
  { letter: 'R', subcategory: 'Rope', products: ['Nylon Rope', 'Polyester Rope', 'Wire Rope'] },
  { letter: 'R', subcategory: 'Respirators', products: ['Dust Masks', 'Half Face Respirators'] },
  { letter: 'S', subcategory: 'Safety Equipment', products: ['Fire Extinguishers', 'Spill Kits', 'Eye Wash Stations'] },
  { letter: 'S', subcategory: 'Sensors', products: ['Proximity Sensors', 'Temperature Sensors', 'Pressure Sensors'] },
  { letter: 'S', subcategory: 'Steel Products', products: ['Flat Bars', 'Round Bars', 'Angles', 'Channels'] },
  { letter: 'S', subcategory: 'Storage', products: ['Tool Cabinets', 'Shelving', 'Lockers'] },
  { letter: 'T', subcategory: 'Toolboxes', products: ['Portable Tool Boxes', 'Tool Cabinets'] },
  { letter: 'T', subcategory: 'Torque Tools', products: ['Torque Wrenches', 'Torque Multipliers'] },
  { letter: 'T', subcategory: 'Test Equipment', products: ['Multimeters', 'Clamp Meters', 'Oscilloscopes'] },
  { letter: 'U', subcategory: 'Ultrasonic Cleaners', products: ['Industrial Cleaning Machines'] },
  { letter: 'U', subcategory: 'UPS Systems', products: ['Uninterruptible Power Supplies'] },
  { letter: 'V', subcategory: 'Valves', products: ['Ball Valves', 'Butterfly Valves', 'Globe Valves', 'Gate Valves', 'Check Valves'] },
  { letter: 'V', subcategory: 'Vacuum Equipment', products: ['Vacuum Pumps', 'Industrial Vacuums'] },
  { letter: 'W', subcategory: 'Welding Equipment', products: ['MIG Welders', 'TIG Welders', 'Stick Welders', 'Plasma Cutters'] },
  { letter: 'W', subcategory: 'Wheels', products: ['Caster Wheels', 'Industrial Wheels'] },
  { letter: 'W', subcategory: 'Washers', products: ['Flat Washers', 'Spring Washers'] },
  { letter: 'X', subcategory: 'X-Ray Equipment', products: ['Industrial NDT X-Ray Machines'] },
  { letter: 'Y', subcategory: 'Yard Equipment', products: ['Pressure Washers', 'Lawn Equipment'] },
  { letter: 'Z', subcategory: 'Zinc Coatings', products: ['Cold Galvanizing Spray', 'Zinc Paint'] },
];
