export type CatalogueEntry = {
  letter: string;
  subcategory: string;
  products: string[];
};

export const INDUSTRIAL_CATALOGUE: CatalogueEntry[] = [
  { letter: 'A', subcategory: 'Air Equipment', products: ['Air Equipment'] },
  { letter: 'A', subcategory: 'Abrasives', products: ['Abrasives'] },
  { letter: 'A', subcategory: 'Adhesives', products: ['Adhesives'] },
  { letter: 'B', subcategory: 'Bearings', products: ['Bearings'] },
  { letter: 'B', subcategory: 'Bolts & Fasteners', products: ['Bolts & Fasteners'] },
  { letter: 'B', subcategory: 'Belts', products: ['Belts'] },
  { letter: 'C', subcategory: 'Cutting Tools', products: ['Cutting Tools'] },
  { letter: 'C', subcategory: 'Chains', products: ['Chains'] },
  { letter: 'C', subcategory: 'Cables', products: ['Cables'] },
  { letter: 'C', subcategory: 'Chemicals', products: ['Chemicals'] },
  { letter: 'D', subcategory: 'Drills', products: ['Drills'] },
  { letter: 'D', subcategory: 'Dust Collection', products: ['Dust Collection'] },
  { letter: 'D', subcategory: 'Diesel Equipment', products: ['Diesel Equipment'] },
  { letter: 'E', subcategory: 'Electric Motors', products: ['Electric Motors'] },
  { letter: 'E', subcategory: 'Electrical Equipment', products: ['Electrical Equipment'] },
  { letter: 'E', subcategory: 'Extension Cords', products: ['Extension Cords'] },
  { letter: 'F', subcategory: 'Fans', products: ['Fans'] },
  { letter: 'F', subcategory: 'Filters', products: ['Filters'] },
  { letter: 'F', subcategory: 'Forklift Accessories', products: ['Forklift Accessories'] },
  { letter: 'G', subcategory: 'Gearboxes', products: ['Gearboxes'] },
  { letter: 'G', subcategory: 'Generators', products: ['Generators'] },
  { letter: 'G', subcategory: 'Gauges', products: ['Gauges'] },
  { letter: 'H', subcategory: 'Hydraulic Equipment', products: ['Hydraulic Equipment'] },
  { letter: 'H', subcategory: 'Hand Tools', products: ['Hand Tools'] },
  { letter: 'H', subcategory: 'Hoists', products: ['Hoists'] },
  { letter: 'I', subcategory: 'Industrial Lighting', products: ['Industrial Lighting'] },
  { letter: 'I', subcategory: 'Inverters', products: ['Inverters'] },
  { letter: 'I', subcategory: 'Insulation', products: ['Insulation'] },
  { letter: 'J', subcategory: 'Jacks', products: ['Jacks'] },
  { letter: 'J', subcategory: 'Jib Cranes', products: ['Jib Cranes'] },
  { letter: 'K', subcategory: 'Knives', products: ['Knives'] },
  { letter: 'K', subcategory: 'Key Stock', products: ['Key Stock'] },
  { letter: 'L', subcategory: 'Ladders', products: ['Ladders'] },
  { letter: 'L', subcategory: 'Lifting Equipment', products: ['Lifting Equipment'] },
  { letter: 'L', subcategory: 'Lubrication Systems', products: ['Lubrication Systems'] },
  { letter: 'M', subcategory: 'Measuring Tools', products: ['Measuring Tools'] },
  { letter: 'M', subcategory: 'Machine Tools', products: ['Machine Tools'] },
  { letter: 'M', subcategory: 'Material Handling', products: ['Material Handling'] },
  { letter: 'N', subcategory: 'Nozzles', products: ['Nozzles'] },
  { letter: 'N', subcategory: 'Nuts', products: ['Nuts'] },
  { letter: 'O', subcategory: 'Oil Equipment', products: ['Oil Equipment'] },
  { letter: 'O', subcategory: 'O-Rings', products: ['O-Rings'] },
  { letter: 'P', subcategory: 'Pumps', products: ['Pumps'] },
  { letter: 'P', subcategory: 'Pneumatic Equipment', products: ['Pneumatic Equipment'] },
  { letter: 'P', subcategory: 'Pipes', products: ['Pipes'] },
  { letter: 'P', subcategory: 'PPE', products: ['PPE'] },
  { letter: 'Q', subcategory: 'Quick Couplings', products: ['Quick Couplings'] },
  { letter: 'R', subcategory: 'Rollers', products: ['Rollers'] },
  { letter: 'R', subcategory: 'Rope', products: ['Rope'] },
  { letter: 'R', subcategory: 'Respirators', products: ['Respirators'] },
  { letter: 'S', subcategory: 'Safety Equipment', products: ['Safety Equipment'] },
  { letter: 'S', subcategory: 'Sensors', products: ['Sensors'] },
  { letter: 'S', subcategory: 'Steel Products', products: ['Steel Products'] },
  { letter: 'S', subcategory: 'Storage', products: ['Storage'] },
  { letter: 'T', subcategory: 'Toolboxes', products: ['Toolboxes'] },
  { letter: 'T', subcategory: 'Torque Tools', products: ['Torque Tools'] },
  { letter: 'T', subcategory: 'Test Equipment', products: ['Test Equipment'] },
  { letter: 'U', subcategory: 'Ultrasonic Cleaners', products: ['Ultrasonic Cleaners'] },
  { letter: 'U', subcategory: 'UPS Systems', products: ['UPS Systems'] },
  { letter: 'V', subcategory: 'Valves', products: ['Valves'] },
  { letter: 'V', subcategory: 'Vacuum Equipment', products: ['Vacuum Equipment'] },
  { letter: 'W', subcategory: 'Welding Equipment', products: ['Welding Equipment'] },
  { letter: 'W', subcategory: 'Wheels', products: ['Wheels'] },
  { letter: 'W', subcategory: 'Washers', products: ['Washers'] },
  { letter: 'X', subcategory: 'X-Ray Equipment', products: ['X-Ray Equipment'] },
  { letter: 'Y', subcategory: 'Yard Equipment', products: ['Yard Equipment'] },
  { letter: 'Z', subcategory: 'Zinc Coatings', products: ['Zinc Coatings'] },
];
