export type CatalogueEntry = {
  letter: string;
  subcategory: string;
  products: string[];
};

export const MARINE_CATALOGUE: CatalogueEntry[] = [
  {
    letter: 'A',
    subcategory: 'Anchors',
    products: ['Stockless', 'Hall', 'AC-14', 'Danforth', 'Plough', 'Bruce anchors'],
  },
  {
    letter: 'A',
    subcategory: 'Anodes',
    products: ['Zinc', 'aluminum', 'magnesium sacrificial anodes'],
  },
  {
    letter: 'A',
    subcategory: 'Air Compressors',
    products: ['Starting air compressors', 'service compressors'],
  },
  {
    letter: 'A',
    subcategory: 'Anti-fouling Paint',
    products: ['Hull anti-growth coatings'],
  },
  { letter: 'B', subcategory: 'Batteries', products: ['Batteries'] },
  { letter: 'B', subcategory: 'Bilge Pumps', products: ['Bilge Pumps'] },
  { letter: 'B', subcategory: 'Bearings', products: ['Bearings'] },
  { letter: 'B', subcategory: 'Binoculars', products: ['Binoculars'] },
  { letter: 'B', subcategory: 'Boat Hooks', products: ['Boat Hooks'] },
  { letter: 'C', subcategory: 'Chains', products: ['Chains'] },
  { letter: 'C', subcategory: 'Cables', products: ['Cables'] },
  { letter: 'C', subcategory: 'Compasses', products: ['Compasses'] },
  { letter: 'C', subcategory: 'Cleaning Chemicals', products: ['Cleaning Chemicals'] },
  { letter: 'C', subcategory: 'Couplings', products: ['Couplings'] },
  { letter: 'D', subcategory: 'Deck Equipment', products: ['Deck Equipment'] },
  { letter: 'D', subcategory: 'Davits', products: ['Davits'] },
  { letter: 'D', subcategory: 'Diesel Filters', products: ['Diesel Filters'] },
  { letter: 'D', subcategory: 'Deck Paint', products: ['Deck Paint'] },
  { letter: 'E', subcategory: 'Engine Spare Parts', products: ['Engine Spare Parts'] },
  { letter: 'E', subcategory: 'Emergency Lights', products: ['Emergency Lights'] },
  { letter: 'E', subcategory: 'Epoxy Products', products: ['Epoxy Products'] },
  { letter: 'F', subcategory: 'Fire Extinguishers', products: ['Fire Extinguishers'] },
  { letter: 'F', subcategory: 'Fire Hoses', products: ['Fire Hoses'] },
  { letter: 'F', subcategory: 'Fenders', products: ['Fenders'] },
  { letter: 'F', subcategory: 'Fuel Pumps', products: ['Fuel Pumps'] },
  { letter: 'G', subcategory: 'Gaskets', products: ['Gaskets'] },
  { letter: 'G', subcategory: 'GPS Systems', products: ['GPS Systems'] },
  { letter: 'G', subcategory: 'Galley Equipment', products: ['Galley Equipment'] },
  { letter: 'H', subcategory: 'Hydraulic Pumps', products: ['Hydraulic Pumps'] },
  { letter: 'H', subcategory: 'Hoses', products: ['Hoses'] },
  { letter: 'H', subcategory: 'Hatch Covers', products: ['Hatch Covers'] },
  { letter: 'I', subcategory: 'Impellers', products: ['Impellers'] },
  { letter: 'I', subcategory: 'Insulation Materials', products: ['Insulation Materials'] },
  { letter: 'I', subcategory: 'Inflatable Boats', products: ['Inflatable Boats'] },
  { letter: 'J', subcategory: 'Jackets', products: ['Life Jackets'] },
  { letter: 'J', subcategory: 'Junction Boxes', products: ['Junction Boxes'] },
  { letter: 'K', subcategory: 'Keys & Key Switches', products: ['Keys & Key Switches'] },
  { letter: 'K', subcategory: 'Knives', products: ['Knives'] },
  { letter: 'L', subcategory: 'Liferafts', products: ['Liferafts'] },
  { letter: 'L', subcategory: 'Lifebuoys', products: ['Lifebuoys'] },
  { letter: 'L', subcategory: 'Lubricants', products: ['Lubricants'] },
  { letter: 'L', subcategory: 'LED Navigation Lights', products: ['LED Navigation Lights'] },
  { letter: 'M', subcategory: 'Mooring Ropes', products: ['Mooring Ropes'] },
  { letter: 'M', subcategory: 'Marine Paints', products: ['Marine Paints'] },
  { letter: 'M', subcategory: 'Marine Chemicals', products: ['Marine Chemicals'] },
  { letter: 'N', subcategory: 'Navigation Equipment', products: ['Navigation Equipment'] },
  { letter: 'N', subcategory: 'Nuts & Bolts', products: ['Nuts & Bolts'] },
  { letter: 'O', subcategory: 'Oil Separators', products: ['Oil Separators'] },
  { letter: 'O', subcategory: 'O-rings', products: ['O-rings'] },
  { letter: 'O', subcategory: 'Outboard Motors', products: ['Outboard Motors'] },
  { letter: 'P', subcategory: 'Pumps', products: ['Pumps'] },
  { letter: 'P', subcategory: 'Propellers', products: ['Propellers'] },
  { letter: 'P', subcategory: 'PPE', products: ['PPE'] },
  { letter: 'P', subcategory: 'Pressure Gauges', products: ['Pressure Gauges'] },
  { letter: 'Q', subcategory: 'Quick Couplings', products: ['Quick Couplings'] },
  { letter: 'Q', subcategory: 'Quick Release Hooks', products: ['Quick Release Hooks'] },
  { letter: 'R', subcategory: 'Radar Systems', products: ['Radar Systems'] },
  { letter: 'R', subcategory: 'Rescue Equipment', products: ['Rescue Equipment'] },
  { letter: 'R', subcategory: 'Rubber Sheets', products: ['Rubber Sheets'] },
  { letter: 'S', subcategory: 'Safety Equipment', products: ['Safety Equipment'] },
  { letter: 'S', subcategory: 'Shackles', products: ['Shackles'] },
  { letter: 'S', subcategory: 'Seals', products: ['Seals'] },
  { letter: 'S', subcategory: 'Steering Systems', products: ['Steering Systems'] },
  { letter: 'S', subcategory: 'Spare Parts', products: ['Spare Parts'] },
  { letter: 'T', subcategory: 'Tools', products: ['Tools'] },
  { letter: 'T', subcategory: 'Tanks', products: ['Tanks'] },
  { letter: 'T', subcategory: 'Thermometers', products: ['Thermometers'] },
  { letter: 'T', subcategory: 'Teak Care Products', products: ['Teak Care Products'] },
  { letter: 'U', subcategory: 'Ultrasonic Cleaners', products: ['Ultrasonic Cleaners'] },
  { letter: 'U', subcategory: 'Underwater Lights', products: ['Underwater Lights'] },
  { letter: 'V', subcategory: 'Valves', products: ['Valves'] },
  { letter: 'V', subcategory: 'VHF Radios', products: ['VHF Radios'] },
  { letter: 'V', subcategory: 'Ventilation Fans', products: ['Ventilation Fans'] },
  { letter: 'W', subcategory: 'Winches', products: ['Winches'] },
  { letter: 'W', subcategory: 'Watermakers', products: ['Watermakers'] },
  { letter: 'W', subcategory: 'Wire Ropes', products: ['Wire Ropes'] },
  { letter: 'W', subcategory: 'Welding Supplies', products: ['Welding Supplies'] },
  { letter: 'X', subcategory: 'X-band Radar', products: ['X-band Radar'] },
  { letter: 'X', subcategory: 'Xenon Searchlights', products: ['Xenon Searchlights'] },
  { letter: 'Y', subcategory: 'Yacht Equipment', products: ['Yacht Equipment'] },
  { letter: 'Y', subcategory: 'Y-Strainers', products: ['Y-Strainers'] },
  { letter: 'Z', subcategory: 'Zinc Anodes', products: ['Zinc Anodes'] },
  { letter: 'Z', subcategory: 'Zinc Spray', products: ['Zinc Spray'] },
];
