export type CatalogueEntry = {
  letter: string;
  subcategory: string;
  products: string[];
};

export const MARINE_CATALOGUE: CatalogueEntry[] = [
  { letter: 'A', subcategory: 'Anchors', products: ['Stockless', 'Hall', 'AC-14', 'Danforth', 'Plough', 'Bruce anchors'] },
  { letter: 'A', subcategory: 'Anodes', products: ['Zinc sacrificial anodes', 'Aluminum sacrificial anodes', 'Magnesium sacrificial anodes'] },
  { letter: 'A', subcategory: 'Air Compressors', products: ['Starting air compressors', 'Service compressors'] },
  { letter: 'A', subcategory: 'Anti-fouling Paint', products: ['Hull anti-growth coatings'] },
  { letter: 'B', subcategory: 'Batteries', products: ['Marine starting batteries', 'Deep-cycle batteries'] },
  { letter: 'B', subcategory: 'Bilge Pumps', products: ['Engine room water removal pumps', 'Compartment water removal pumps'] },
  { letter: 'B', subcategory: 'Bearings', products: ['Shaft bearings', 'Engine bearings', 'Machinery bearings'] },
  { letter: 'B', subcategory: 'Binoculars', products: ['Marine-grade navigation binoculars'] },
  { letter: 'B', subcategory: 'Boat Hooks', products: ['Docking boat hooks', 'Line retrieval boat hooks'] },
  { letter: 'C', subcategory: 'Chains', products: ['Anchor chains', 'Stud-link chains', 'Mooring chains'] },
  { letter: 'C', subcategory: 'Cables', products: ['Electrical cables', 'Engine control cables', 'Communication cables'] },
  { letter: 'C', subcategory: 'Compasses', products: ['Magnetic navigation compasses', 'Gyro navigation compasses'] },
  { letter: 'C', subcategory: 'Cleaning Chemicals', products: ['Deck cleaners', 'Tank cleaners', 'Engine degreasers'] },
  { letter: 'C', subcategory: 'Couplings', products: ['Flexible shaft couplings', 'Pump couplings'] },
  { letter: 'D', subcategory: 'Deck Equipment', products: ['Winches', 'Capstans', 'Fairleads', 'Bollards'] },
  { letter: 'D', subcategory: 'Davits', products: ['Lifeboat launching davits', 'Rescue boat launching davits'] },
  { letter: 'D', subcategory: 'Diesel Filters', products: ['Fuel filtration', 'Oil filtration'] },
  { letter: 'D', subcategory: 'Deck Paint', products: ['Protective deck coatings'] },
  { letter: 'E', subcategory: 'Engine Spare Parts', products: ['Pistons', 'Liners', 'Valves', 'Gaskets', 'Injectors'] },
  { letter: 'E', subcategory: 'Emergency Lights', products: ['SOLAS-approved emergency lighting'] },
  { letter: 'E', subcategory: 'Epoxy Products', products: ['Hull repair compounds', 'Structural repair compounds'] },
  { letter: 'F', subcategory: 'Fire Extinguishers', products: ['CO₂ fire extinguishers', 'Foam fire extinguishers', 'Dry Powder fire extinguishers'] },
  { letter: 'F', subcategory: 'Fire Hoses', products: ['Marine fire-fighting hose assemblies'] },
  { letter: 'F', subcategory: 'Fenders', products: ['Pneumatic fenders', 'Foam fenders', 'Rubber docking fenders'] },
  { letter: 'F', subcategory: 'Fuel Pumps', products: ['Marine diesel transfer pumps', 'Marine diesel supply pumps'] },
  { letter: 'G', subcategory: 'Gaskets', products: ['Engine gaskets', 'Flange gaskets', 'Pump sealing gaskets'] },
  { letter: 'G', subcategory: 'GPS Systems', products: ['Marine satellite navigation GPS'] },
  { letter: 'G', subcategory: 'Galley Equipment', products: ['Commercial kitchen appliances', 'Commercial kitchen utensils'] },
  { letter: 'H', subcategory: 'Hydraulic Pumps', products: ['Steering hydraulics', 'Deck machinery hydraulics'] },
  { letter: 'H', subcategory: 'Hoses', products: ['Fuel hoses', 'Hydraulic hoses', 'Cooling hoses', 'Air hoses'] },
  { letter: 'H', subcategory: 'Hatch Covers', products: ['Cargo hold weather-tight covers'] },
  { letter: 'I', subcategory: 'Impellers', products: ['Cooling water pump impellers'] },
  { letter: 'I', subcategory: 'Insulation Materials', products: ['Thermal insulation', 'Acoustic insulation'] },
  { letter: 'I', subcategory: 'Inflatable Boats', products: ['Rescue boats', 'Work boats'] },
  { letter: 'J', subcategory: 'Jackets (Life Jackets)', products: ['SOLAS-approved life jackets'] },
  { letter: 'J', subcategory: 'Junction Boxes', products: ['Marine electrical distribution boxes'] },
  { letter: 'K', subcategory: 'Keys & Key Switches', products: ['Engine control keys', 'Electrical control accessories'] },
  { letter: 'K', subcategory: 'Knives', products: ['Rigging knives', 'Safety knives', 'Rescue knives'] },
  { letter: 'L', subcategory: 'Liferafts', products: ['Inflatable emergency survival rafts'] },
  { letter: 'L', subcategory: 'Lifebuoys', products: ['Ring buoys with lights', 'Ring buoys with smoke signals'] },
  { letter: 'L', subcategory: 'Lubricants', products: ['Engine oils', 'Gear oils', 'Hydraulic oils', 'Greases'] },
  { letter: 'L', subcategory: 'LED Navigation Lights', products: ['Marine-certified navigation lighting'] },
  { letter: 'M', subcategory: 'Mooring Ropes', products: ['Nylon ropes', 'Polypropylene ropes', 'HMPE ropes', 'Polyester ropes'] },
  { letter: 'M', subcategory: 'Marine Paints', products: ['Hull protective coatings', 'Structural protective coatings'] },
  { letter: 'M', subcategory: 'Marine Chemicals', products: ['Water treatment chemicals', 'Boiler chemicals', 'Marine cleaners'] },
  { letter: 'N', subcategory: 'Navigation Equipment', products: ['Radar', 'AIS', 'GPS', 'Echo Sounders'] },
  { letter: 'N', subcategory: 'Nuts & Bolts', products: ['Marine-grade stainless steel fasteners'] },
  { letter: 'O', subcategory: 'Oil Separators', products: ['Oily water separator systems'] },
  { letter: 'O', subcategory: 'O-rings', products: ['Rubber sealing rings'] },
  { letter: 'O', subcategory: 'Outboard Motors', products: ['Portable marine engines'] },
  { letter: 'P', subcategory: 'Pumps', products: ['Ballast pumps', 'Bilge pumps', 'Cargo pumps', 'Fire pumps', 'Sewage pumps'] },
  { letter: 'P', subcategory: 'Propellers', products: ['Bronze propellers', 'Stainless steel propellers'] },
  { letter: 'P', subcategory: 'PPE', products: ['Helmets', 'Gloves', 'Goggles', 'Coveralls', 'Boots'] },
  { letter: 'P', subcategory: 'Pressure Gauges', products: ['Engine pressure monitoring', 'Hydraulic pressure monitoring'] },
  { letter: 'Q', subcategory: 'Quick Couplings', products: ['Hydraulic connectors', 'Pneumatic connectors'] },
  { letter: 'Q', subcategory: 'Quick Release Hooks', products: ['Mooring safety release systems'] },
  { letter: 'R', subcategory: 'Radar Systems', products: ['Marine navigation radar'] },
  { letter: 'R', subcategory: 'Rescue Equipment', products: ['Rescue baskets', 'Stretchers', 'Throw lines'] },
  { letter: 'R', subcategory: 'Rubber Sheets', products: ['Industrial sealing materials'] },
  { letter: 'S', subcategory: 'Safety Equipment', products: ['SOLAS compliant safety products', 'IMO compliant safety products'] },
  { letter: 'S', subcategory: 'Shackles', products: ['Bow shackles', 'Dee shackles', 'Anchor shackles'] },
  { letter: 'S', subcategory: 'Seals', products: ['Mechanical seals', 'Oil seals'] },
  { letter: 'S', subcategory: 'Steering Systems', products: ['Hydraulic steering gear', 'Mechanical steering gear'] },
  { letter: 'S', subcategory: 'Spare Parts', products: ['OEM machinery spares', 'Aftermarket machinery spares'] },
  { letter: 'T', subcategory: 'Tools', products: ['Hand tools', 'Power tools', 'Torque tools'] },
  { letter: 'T', subcategory: 'Tanks', products: ['Fuel tanks', 'Freshwater tanks', 'Sewage tanks', 'Hydraulic tanks'] },
  { letter: 'T', subcategory: 'Thermometers', products: ['Engine monitoring instruments'] },
  { letter: 'T', subcategory: 'Teak Care Products', products: ['Teak cleaners', 'Teak oils', 'Teak sealers'] },
  { letter: 'U', subcategory: 'Ultrasonic Cleaners', products: ['Precision cleaning equipment'] },
  { letter: 'U', subcategory: 'Underwater Lights', products: ['Marine LED underwater lighting'] },
  { letter: 'V', subcategory: 'Valves', products: ['Ball valves', 'Globe valves', 'Butterfly valves', 'Gate valves', 'Check valves'] },
  { letter: 'V', subcategory: 'VHF Radios', products: ['Marine communication systems'] },
  { letter: 'V', subcategory: 'Ventilation Fans', products: ['Engine room ventilation'] },
  { letter: 'W', subcategory: 'Winches', products: ['Anchor winches', 'Towing winches', 'Cargo handling winches'] },
  { letter: 'W', subcategory: 'Watermakers', products: ['Reverse osmosis freshwater generators'] },
  { letter: 'W', subcategory: 'Wire Ropes', products: ['Galvanized wire ropes', 'Stainless steel wire ropes'] },
  { letter: 'W', subcategory: 'Welding Supplies', products: ['Electrodes', 'Welding helmets', 'Welding machines'] },
  { letter: 'X', subcategory: 'X-band Radar', products: ['X-band frequency marine radar'] },
  { letter: 'X', subcategory: 'Xenon Searchlights', products: ['High-intensity marine searchlights'] },
  { letter: 'Y', subcategory: 'Yacht Equipment', products: ['Premium yacht accessories', 'Premium yacht fittings'] },
  { letter: 'Y', subcategory: 'Y-Strainers', products: ['Pipeline filtration equipment'] },
  { letter: 'Z', subcategory: 'Zinc Anodes', products: ['Hull corrosion protection anodes', 'Propeller corrosion protection anodes'] },
  { letter: 'Z', subcategory: 'Zinc Spray', products: ['Cold galvanizing anti-corrosion coating'] },
];
