export const ADMIN_NAV = [
  { title: 'Dashboard', href: '/admin', icon: 'LayoutDashboard' },
  { title: 'Orders', href: '/admin/orders', icon: 'ShoppingBag' },
  { title: 'Customers', href: '/admin/customers', icon: 'Users' },
  { title: 'Products', href: '/admin/products', icon: 'Package' },
  { title: 'Categories', href: '/admin/categories', icon: 'FolderTree' },
  { title: 'Subcategories', href: '/admin/subcategories', icon: 'GitBranch' },
  { title: 'Brands', href: '/admin/brands', icon: 'Award' },
  { title: 'Inventory', href: '/admin/inventory', icon: 'Warehouse' },
  { title: 'Discounts', href: '/admin/discounts', icon: 'Percent' },
  { title: 'Future Products', href: '/admin/future-products', icon: 'Clock' },
  { title: 'Upcoming', href: '/admin/upcoming', icon: 'Calendar' },
  { title: 'Fast Selling', href: '/admin/fast-selling', icon: 'TrendingUp' },
  { title: 'Blogs', href: '/admin/blogs', icon: 'FileText' },
  { title: 'News', href: '/admin/news', icon: 'Newspaper' },
  { title: 'Gallery', href: '/admin/gallery', icon: 'Images' },
  { title: 'Media Library', href: '/admin/media', icon: 'Image' },
  { title: 'Email Templates', href: '/admin/email-templates', icon: 'Mail' },
  { title: 'Shipping', href: '/admin/shipping', icon: 'Truck' },
  { title: 'Tracking', href: '/admin/tracking', icon: 'MapPin' },
  { title: 'Users', href: '/admin/users', icon: 'UserCog' },
  { title: 'Roles', href: '/admin/roles', icon: 'Shield' },
  { title: 'Permissions', href: '/admin/permissions', icon: 'Key' },
  { title: 'Settings', href: '/admin/settings', icon: 'Settings' },
  { title: 'Reports', href: '/admin/reports', icon: 'BarChart3' },
  { title: 'Activity Logs', href: '/admin/activity-logs', icon: 'Activity' },
  { title: 'Suggestions', href: '/admin/suggestions', icon: 'MessageSquare' },
  { title: 'SEO', href: '/admin/seo', icon: 'Search' },
  { title: 'Backup', href: '/admin/backup', icon: 'Database' },
  { title: 'System Logs', href: '/admin/system-logs', icon: 'Terminal' },
] as const;
